"""Initial tables

Revision ID: 479550115cf6
Revises: 
Create Date: 2025-12-30 15:13:52.431303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '479550115cf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_name', sa.String(), nullable=True),
    sa.Column('room_number', sa.Integer(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enclosures_id'), 'enclosures', ['id'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('life_expectancy', sa.Integer(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('habitat', sa.String(), nullable=True),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_species_extra_info_gin', 'species', ['extra_info'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('enclosure_id', sa.Integer(), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enclosure_id'], ['enclosures.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_index('ix_species_extra_info_gin', table_name='species', postgresql_using='gin')
    op.drop_table('species')
    op.drop_index(op.f('ix_enclosures_id'), table_name='enclosures')
    op.drop_table('enclosures')
    # ### end Alembic commands ###
