CREATE USER zoo_admin WITH PASSWORD 'zoo_pass';
CREATE DATABASE zoo_db OWNER zoo_admin;
GRANT ALL PRIVILEGES ON DATABASE zoo_db TO zoo_admin;

-- task 6
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;